### ISSUE TITLE
u- cursive joins

### ISSUE THREAD

**Issue by simoncozens** [SorkinType/VICWANTSchoolhandAustralia#1]
Was just testing the accented glyphs in the cursive and noticed this:

![shape](https://github.com/SorkinType/VICWANTSchoolhandAustralia/assets/106728/1043810f-fee0-4415-8c41-b68a6139c259)

It isn't just the final glyphs:

<img width="985" alt="Screenshot 2024-04-22 at 13 25 36" src="https://github.com/SorkinType/VICWANTSchoolhandAustralia/assets/106728/8e56a399-6207-46c1-97f0-883aaffea252">

Maybe we need to alter the RSB of u.cv02? But I will leave that for @EbenSorkin

**Comment by EbenSorkin** [comment]
I fixed these and a big raft of other issues I noticed.

**Comment by simoncozens** [comment]
Thank you!
